services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres-data:
